version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    volumes:
      - mongo:/data/db

  app:
    build: .
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DB_URI: ${DB_URI}
    depends_on:
      - mongo

volumes:
  mongo: {}
